// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Message = __t.object("Message", {
  id: __t.u64(),
  threadId: __t.u64(),
  role: __t.string(),
  content: __t.string(),
  metadata: __t.string(),
  createdAt: __t.timestamp(),
});
export type Message = __Infer<typeof Message>;

export const Thread = __t.object("Thread", {
  id: __t.u64(),
  userId: __t.u64(),
  title: __t.string(),
  createdAt: __t.timestamp(),
});
export type Thread = __Infer<typeof Thread>;

export const User = __t.object("User", {
  id: __t.u64(),
  email: __t.string(),
  passwordHash: __t.string(),
  createdAt: __t.timestamp(),
});
export type User = __Infer<typeof User>;

