// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CreateThreadReducer from "../create_thread_reducer";
import CreateUserReducer from "../create_user_reducer";
import DeleteThreadReducer from "../delete_thread_reducer";
import InsertMessageReducer from "../insert_message_reducer";
import UpdateMessageMetadataReducer from "../update_message_metadata_reducer";

export type CreateThreadParams = __Infer<typeof CreateThreadReducer>;
export type CreateUserParams = __Infer<typeof CreateUserReducer>;
export type DeleteThreadParams = __Infer<typeof DeleteThreadReducer>;
export type InsertMessageParams = __Infer<typeof InsertMessageReducer>;
export type UpdateMessageMetadataParams = __Infer<typeof UpdateMessageMetadataReducer>;

